import {sidebar} from "vuepress-theme-hope";

export const zhSidebar = sidebar({
    "/": [
        "",
        "/about/intro",
    ],
    '/collect': "structure",
    '/back/java/': "structure",
    '/back/struts/': "structure",
    '/back/spring/': "structure",
    '/back/spring-security/': "structure",
    '/back/spring-boot/': "structure",
    '/back/spring-cloud/': "structure",
    '/back/job/quartz/': "structure",
    '/back/mybatis/': "structure",
    '/back/distributed/': "structure",
    '/back/message-queue/': "structure",
    '/ops/os/linux/': "structure",
    '/ops/os/mac/': "structure",
    '/ops/server/nginx/': "structure",
    '/ops/server/apache/': "structure",
    '/ops/server/tomcat/': "structure",
    '/tools/git/': "structure",
    '/ops/sonar/': "structure",
    '/db/redis/': "structure",
    '/db/oracle/': "structure",
    '/db/mysql/': "structure",
    '/other/debugger/': "structure",
    '/other/optimize/': "structure",
    '/other/pdf/': "structure",
    '/front/vue/': "structure",
    '/front/js/': "structure",
    '/network/protocol/': "structure",
    '/network/grab/': "structure",
    '/ops/virtualization/k8s/': "structure",
});
